routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/product','ProductController@index');
Route::get('/preorder','PreorderController@index');


Route::get('signin', 'SigninController@form')->name('signin.form');
Route::post('attempt', 'SigninController@attempt')->name('signin.attempt');

Auth::routes();
/*
Route::group(['middleware' => 'auth'], function ()
{
*/
	Route::group(['prefix' => 'dashboard'], function ()
	{
		Route::get('/webtools','DashboardWebtoolsController@index');
		Route::get('/','DashboardActivationController@index');
		Route::get('stores/{store_name}', ['uses' => 'DashboardWebtoolsController@store_detail']);
		Route::get('stores','DashboardActivationController@get_store_sales_daily');
	});

	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index');
/*
});
*/
Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/web','FrontPageController@index');
	Route::get('/home', 'HomeController@index')->name('home');

	Route::resource('region', 'RegionController');

	/**
	 * Config
	*/
	Route::get('config','ConfigController@index')->name('config');
	Route::resource('config/user','UserController');
	Route::resource('config/role', 'RoleController');
	Route::resource('config/permission', 'PermissionController');
	Route::resource('config/menu', 'MenuController');

	/**
	 * User Profile
	*/
	Route::get('web/profile', ['as' => 'web.profile', 'uses' => 'UserProfileController@frontpage_profile']);
	Route::get('web/profile/reset_password', ['as' => 'web.profile.reset_password', 'uses' => 'ChangePasswordFrontPageController@reset_password']);
	Route::post('web/profile/riset_password_submit', ['as' => 'web.profile.reset_password_submit', 'uses' => 'ChangePasswordFrontPageController@reset_password_submit']);
	Route::get('profile', 'UserProfileController@index')->name('profile.view');
	Route::get('profile/change_password', 'UserProfileController@change_password')->name('profile.change_password');
	Route::get('profile/{id}/edit', 'UserProfileController@edit');
	Route::patch('profile/{id}', 'UserProfileController@update');
	Route::post('profile/change_password', 'UserProfileController@change_password_submit');

	/**
	 * Product
	*/
	Route::get('/product','ProductController@index');
	
	/**
	 * Pre-Order
	 */
	Route::resource('preorder/manage', 'PreOrderController', ['as' => 'preorder']);
	Route::get('preorder/manage/{preorder_id}/transactions','PreOrderController@transactions')->name('preorder.manage.transactions');
	Route::get('preorder/manage/{preorder_id}/store-report','PreOrderController@store_report')->name('preorder.manage.store_report');
	Route::post('preorder/confirm-payment', 'PreOrderTransactionController@confirm_payment');
	Route::post('preorder/restore-transaction', 'PreOrderTransactionController@restore_trans');
	Route::resource('preorder','PreOrderTransactionController');

	/**
	 * Sales Order
	 */
	Route::get('/web/salesorder','SalesorderController@index');
	Route::get('/web/salesorder/all','SalesorderController@index_all');
	Route::get('/web/salesorder/export', ['uses' => 'SalesorderController@export']);
	Route::get('/web/salesorder/create','SalesorderController@create');
	Route::post('/web/salesorder','SalesorderController@store');
	Route::get('/web/salesorder/{salesorder_id}', ['uses' => 'SalesorderController@show']);
	Route::get('/web/salesorder/{salesorder_id}/edit', ['uses' => 'SalesorderController@edit']);
	Route::post('/web/salesorder/{salesorder_id}/update', ['uses' => 'SalesorderController@update']);
	Route::get('/web/salesorder/{salesorder_id}/delete', ['uses' => 'SalesorderController@destroy']);
	Route::get('/web/salesorder/{salesorder_code}/attachment', ['uses' => 'SalesorderController@add_attachment']);
	Route::post('/web/salesorder/{salesorder_code}/store-attachment', 'SalesorderController@store_attachment');
	Route::get('/web/salesorder/{attachment_id}/delete-attachment', ['uses' => 'SalesorderController@destroy_attachment']);
	Route::get('/web/salesorder/{salesorder_code}/verification', ['uses' => 'SalesorderController@verification']);
	Route::get('/web/salesorder/{salesorder_id}/revision', ['uses' => 'SalesorderController@revision']);
	Route::get('/web/salesorder/{salesorder_id}/submit', ['uses' => 'SalesorderController@submit']);
	Route::get('/web/salesorder/{salesorder_id}/reject', ['uses' => 'SalesorderController@reject']);
	Route::get('/web/salesorder/{salesorder_id}/reverification', ['uses' => 'SalesorderController@reverification']);

	Route::get('/web/quotation/json', ['uses' => 'SalesorderController@json']);
	Route::post('/data/salesorder','SalesorderController@getQuotation')->name('dataSalesorder');

	Route::get('/salesorder',['uses' => 'SalesorderController@index_manage']);
	Route::get('/salesorder/{salesorder_id}', ['uses' => 'SalesorderController@show_manage']);
	Route::get('/salesorder/{salesorder_id}/pick', ['uses' => 'SalesorderController@pick_salesorder']);
	Route::get('/salesorder/{salesorder_id}/activation', ['uses' => 'SalesorderController@activation_salesorder']);
	Route::get('/salesorder/{salesorder_id}/activated', ['uses' => 'SalesorderController@activated_salesorder']);
	// Route::post('/salesorder/{salesorder_id}/change-update', ['uses' => 'SalesorderController@save_change_salesorder']);
	// hatihati ini
	// Route::get('/salesorder/{salesorder_id}/check', ['uses' => 'SalesorderController@check_salesorder']);
	Route::get('/salesorder/{salesorder_id}/done', ['uses' => 'SalesorderController@done_salesorder']);

	Route::post('/salesorder/{salesorder_id}/remarks', ['uses' => 'SalesorderRemarksController@store_remarks']);
	Route::get('/salesorder/{salesorder_id}/check-device', ['uses' => 'SalesorderController@check_device']);
	Route::post('/salesorder/{salesorder_id}/update-device', ['uses' => 'SalesorderController@update_device']);
	Route::post('/salesorder/export/param', ['uses' => 'SalesorderController@export_param']);

	/**
	 * Sales Order Transaction
	 */
	Route::post('/web/salesorder/{salesorder_id}', 'SalesorderTransactionController@store');
	Route::get('/web/salesorder/transaction/{transaction_id}/edit', ['uses' => 'SalesorderTransactionController@edit']);
	Route::post('/web/salesorder/transaction/{transaction_id}/update', ['uses' => 'SalesorderTransactionController@update']);
	Route::get('/web/salesorder/transaction/{transaction_id}/delete', ['uses' => 'SalesorderTransactionController@destroy']);
	Route::post('/web/salesorder/transaction/{salesorder_id}/import', ['uses' => 'SalesorderTransactionController@import']);
	Route::get('/web/salesorder/transaction/{salesorder_id}/export', ['uses' => 'SalesorderTransactionController@export']);
	Route::get('/web/salesorder/transaction/{salesorder_id}/request-sim-card', ['uses' => 'SalesorderTransactionController@request_sim']);	

	Route::get('/salesorder/transaction/{salesorder_id}/create', ['uses' => 'SalesorderTransactionController@create_manage']);
	Route::post('/salesorder/transaction/{salesorder_id}/store', ['uses' => 'SalesorderTransactionController@store_manage']);
	Route::get('/salesorder/transaction/{transaction_id}/edit', ['uses' => 'SalesorderTransactionController@edit_manage']);
	Route::post('/salesorder/transaction/{transaction_id}/update', ['uses' => 'SalesorderTransactionController@update_manage']);
	Route::get('/salesorder/transaction/{transaction_id}/delete', ['uses' => 'SalesorderTransactionController@destroy_manage']);

	/**
	 * Sales Order Shipment
	 */
	Route::get('/salesorder/shipment/{salesorder_id}/create', ['uses' => 'SalesorderShipmentController@create']);
	Route::post('/salesorder/shipment/{salesorder_id}/store', ['uses' => 'SalesorderShipmentController@store']);
	Route::get('/salesorder/shipment/{shipment_id}/edit', ['uses' => 'SalesorderShipmentController@edit']);
	Route::post('/salesorder/shipment/{shipment_id}/update', ['uses' => 'SalesorderShipmentController@update']);
	Route::get('/delivery/courier/shipment/{shipment_id}', 'SalesorderShipmentController@courier');
	Route::get('/shipment/export/{ship_id}', 'SalesorderShipmentController@export');
	
	/**
	 * Sales Order DR
	 */
	Route::get('/salesorder/delivery/{salesorder_id}/create', ['uses' => 'SalesorderDeliveryRequestController@create']);
	Route::post('/salesorder/delivery/{salesorder_id}/store', ['uses' => 'SalesorderDeliveryRequestController@store']);
	Route::get('/salesorder/delivery/{so_dr_id}/edit', ['uses' => 'SalesorderDeliveryRequestController@edit']);
	Route::post('/salesorder/delivery/{so_dr_id}/update', ['uses' => 'SalesorderDeliveryRequestController@update']);

// paling atas ini bisa diapus nanti
	Route::get('/delivery/export/{so_dr_id}', 'SalesorderDeliveryRequestController@export');
	Route::post('/salesorder/delivery/{so_dr_id}/verification', ['uses' => 'SalesorderDeliveryRequestController@verification']);
	// Route::post('/salesorder/delivery/{so_dr_id}/signed', ['uses' => 'SalesorderDeliveryRequestController@signed']);
	Route::get('/delivery/courier/dr/{so_dr_id}', 'SalesorderDeliveryRequestController@courier');


	Route::get('/salesorder/delivery/{so_dr_id}/edit/edit', ['uses' => 'SalesorderDeliveryRequestController@edit_edit']);
	Route::post('/salesorder/delivery/{so_dr_id}/update/edit', ['uses' => 'SalesorderDeliveryRequestController@update_edit']);


	/**
	 * Delivery Request
	 */
	Route::get('/delivery/{so_dr_id}', ['uses' => 'DeliveryRequestController@index']);
	Route::post('/delivery/{salesorder_id}/store', ['uses' => 'DeliveryRequestController@store']);
	Route::post('/delivery/{dr_id}/update', ['uses' => 'DeliveryRequestController@update']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
     protected $fillable = [
        'username',
        'fullname',
        'nik',
        'phone',
        'email',
        'password',
        'manager_id',
        'region_id',
        'store_id',
        'last_login',
        'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Relation to Region
     *
     * @return Obj Data Object ID
     */
    public function region()
    {
        return $this->belongsTo('App\Region');
    }

    // public function activations()
    // {
    //     return $this->hasMany('App\Activation', 'proceed_by');
    // }

    // public function store()
    // {
    //     return $this->belongsTo('App\Store');
    // }

    // public function profile()
    // {
    //     return $this->hasOne(UAProfile::class, 'user_id');
    // }

    // public function user_quiz(){
    //     return $this->hasMany(UAUserQuiz::class, 'user_id');
    // }

    public function getLoginDateAttribute()
    {

        return $this->last_login != null ? \Carbon\Carbon::parse($this->last_login)->diffForHumans() : '';
    }

    public function getCreateAtAttribute()
    {
        return $this->created_at != null ? $this->created_at : '';
    }

    public function getUserStatusAttribute()
    {
        if($this->status == 2)
        {
            return "<span class='badge badge-danger'>In-Active</span>";
        }else{
            return "<span class='badge badge-success'>Active</span>";
        }
    }
}

resources/views/admin/user/add_user.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.configuration_tab')
    <!-- Tab panes -->
    <div id="config-user" class="tab-content">
        <div role="tabpanel" class="tab-pane active">
            @include('layouts.error')
            {!! Form::open(['class' => 'form-horizontal', 'action' => 'UserController@store']) !!}
            @include('admin.user.form_user', ['submitButtonText' => 'Create User'])
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/user/edit_admin_error.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.configuration_tab')
    <!-- Tab panes -->
    <div id="config-user" class="tab-content">
        <div role="tabpanel" class="tab-pane active">
            <p>You are not allowed to edit <strong>"ADMINISTRATOR"</strong> users.</p>
            <br/>
            <a href="/config/user" class="btn btn-primary btn-sm m-1">Back</a>
        </div>
    </div>
@endsection

resources/views/admin/user/edit_user.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.configuration_tab')
    <!-- Tab panes -->
    <div id="config-user" class="tab-content">
        <div role="tabpanel" class="tab-pane active">
            @include('layouts.error')

            {!! Form::model($user, ['method' => 'PATCH', 'action' => ['UserController@update', $user->id], 'class' => 'form-horizontal']) !!}
            @include('admin.user.form_user', ['submitButtonText' => 'Update User'])
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/user/form_user.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="form-group row{{ $errors->has('username') ? ' has-error' : '' }}">
            {!! Form::label('username', 'Username', ['class' => 'col-md-4 col-form-label']) !!}

            <div class="col-md-8">
                {!! Form::text('username',null,['class' => 'form-control m-1', 'required' => 'required']) !!}
            </div>
        </div>

        <div class="form-group row{{ $errors->has('email') ? ' has-error' : '' }}">
            {!! Form::label('email', 'Email Address', ['class' => 'col-md-4 col-form-label']) !!}
            
            <div class="col-md-8">
                {!! Form::text('email',null ,['class' => 'form-control m-1', 'required' => 'required']) !!}
            </div>
        </div>

        <div class="form-group row{{ $errors->has('fullname') ? ' has-error' : '' }}">
            {!! Form::label('fullname', 'Full Name', ['class' => 'col-md-4 col-form-label', 'required' => 'required']) !!}

            <div class="col-md-8">
                {!! Form::text('fullname',null,['class' => 'form-control m-1', 'required' => 'required']) !!}
            </div>
        </div>
        
        <div class="form-group row{{ $errors->has('nik') ? ' has-error' : '' }}">
            {!! Form::label('nik', 'NIK', ['class' => 'col-md-4 col-form-label']) !!}

            <div class="col-md-8">
                {!! Form::text('nik',null,['class' => 'form-control m-1']) !!}
            </div>
        </div>
        
        <div class="form-group row{{ $errors->has('phone') ? ' has-error' : '' }}">
            {!! Form::label('phone', 'Mobile Phone', ['class' => 'col-md-4 col-form-label']) !!}

            <div class="col-md-8">
                {!! Form::text('phone',null,['class' => 'form-control m-1']) !!}
            </div>
        </div>
        
        <div class="form-group row{{ $errors->has('password') ? ' has-error' : '' }}">
            {!! Form::label('password', 'Password', ['class' => 'col-md-4 col-form-label']) !!}

            <div class="col-md-8">
                @if($submitButtonText == "Create User")
                    {!! Form::password('password', ['class' => 'form-control m-1', 'required' => 'required']) !!}
                @else
                    {!! Form::password('password', ['class' => 'form-control m-1']) !!}
                @endif
            </div>
        </div>

        <div class="form-group row">
            {!! Form::label('password-confirm', 'Confirm Password', ['class' => 'col-md-4 col-form-label']) !!}

            <div class="col-md-8">
                @if($submitButtonText == "Create User")
                    {!! Form::password('password_confirmation', ['class' => 'form-control m-1', 'required' => 'required']) !!}
                @else
                    {!! Form::password('password_confirmation', ['class' => 'form-control m-1']) !!}
                @endif
            </div>
        </div>            
    </div>
    <div class="col-md-6">
        <div class="form-group row{{ $errors->has('role') ? ' has-error' : '' }}">
            {!! Form::label('role', 'User Role', ['class' => 'col-md-3 col-form-label']) !!}
            
            <div class="col-md-8">
                {!! Form::select('role[]', $roles , $active_role, ['class' => 'form-control chosen-select',  'data-placeholder' => '  - Select -', 'required' => 'required', 'multiple']) !!}
            </div>
        </div>
        <div class="form-group row{{ $errors->has('region') ? ' has-error' : '' }}">
            {!! Form::label('region_id', 'Region', ['class' => 'col-md-3 col-form-label']) !!}
            
            <div class="col-md-8">
                {!! Form::select('region_id', $region , $active_region, ['class' => 'form-control chosen-select', 'required' => 'required']) !!}
            </div>
        </div>
        <div class="form-group row{{ $errors->has('manager') ? ' has-error' : '' }}">
            {!! Form::label('manager_id', 'Manager', ['class' => 'col-md-3 col-form-label']) !!}
            
            <div class="col-md-8">
                {!! Form::select('manager_id', $manager , $active_manager, ['class' => 'form-control chosen-select']) !!}
            </div>
        </div> 
        <div class="form-group row{{ $errors->has('status') ? ' has-error' : '' }}">
            {!! Form::label('status', 'Status', ['class' => 'col-md-3 col-form-label']) !!}
            
            <div class="col-md-8">
                {!! Form::select('status', $status , null, ['class' => 'form-control', 'placeholder' => '--Select--']) !!}
            </div>
        </div>          
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group row">
            <div class="col-md-8 col-md-offset-4">
                <a href="/config/user" class="btn btn-secondary btn-sm m-1">Cancel</a>
                {!! Form::submit( $submitButtonText , ['class'  => 'btn btn-primary btn-sm m-1']) !!}
            </div>
        </div> 
    </div>
</div>

resources/views/admin/user/index_user.blade.php
@extends('layouts.app')

@section('content')
	<div class="btn-group pull-right" role="group">
		<a href="{{ route('user.create') }}" type="button" class="btn btn-success btn-sm m-1">Add User</a>
	</div>
	@include('layouts.configuration_tab')
	
	<!-- Tab panes -->
	<div id="config-user" class="tab-content">
		<div role="tabpanel" class="tab-pane active">
			@if (session('message'))
                <div class="alert alert-{{ session('status') }}">
                    <a class="close" onclick="this.parentElement.style.display='none';" data-dismiss="alert"
                    aria-label="close">&times;</a> {{ session('message') }}
                </div>
            @endif
            <div class="table-wrapper container" style="overflow-y: hidden; overflow-x: auto;">
                <table id="example" class="table table-striped table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th style="width:1%;">No</th>
                            <th style="text-align:center; width:10%;">Username</th>
                            <th style="text-align:center; width:18%;">Name</th>
                            <th style="text-align:center; width:17%;">Role</th>
                            <th style="text-align:center; width:21%;">Region</th>
                            <th style="text-align:center; width:16%;">Added Date</th>
                            <th style="text-align:center; width:12%;">Last Login</th>
                            <th style="text-align:center; width:2%;">Status</th>
                            <th style="text-align:center; width:1%;">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td style="text-align:center;"> {{$loop->iteration}} </td>
                            <td> {{$user->username}} </td>
                            <td> {{$user->fullname}} </td>
                            <td> {{$user->role}} </td>
                            <td> {{$user->region['name']}} </td>
                            <td>{!! $user->create_at !!}</td>
							<td style="text-align:center;">{!! $user->login_date !!}</td>
							<td>{!! $user->user_status !!}</td>
                            <td style="text-align:center;"><a href="/config/user/{{ $user->id }}/edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
			<div class="row mt-4">
				<div class="col-md-2">
					<table class="table">
						<tr>
							<th>User Statistic</th>
						</tr>
					</table>
				</div>
				<div class="col-md-2">
					<table class="table">
						<tr>
							<td>Total Users</td>
							<td class="text-center"><span class="text-muted">{{$total_users}}</span></td>
						</tr>
					</table>
				</div>
				<div class="col-md-2">
					<table class="table">
						<tr>
							<td>Active Users</td>
							<td class="text-center"><span class="text-muted">{{$active_users}}</span></td>
						</tr>
					</table>
				</div>
				<div class="col-md-3">
					<table class="table">
						<tr>
							<td>Today Active Users</td>
							<td class="text-center"><span class="text-muted">{{$today_active}}</span></td>
						</tr>
					</table>
				</div>
				<div class="col-md-3">
					<table class="table">
						<tr>
							<td>Total Disabled Users</td>
							<td class="text-center"><span class="text-muted">{{$disable_users}}</span></td>
						</tr>
					</table>
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
    <!-- <style>
    thead input {
        width: 100%;
    }
    th, td { 
        font-size: 12px;
    }
    .table tbody tr td{
        padding-top:4px;
        padding-bottom:4px;
    }
    </style> -->
@endsection

@section('scripts')
    @parent
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script>
    $(document).ready(function() {
	    $('#example thead tr').clone(true).appendTo( '#example thead' );
        $('#example thead tr:eq(1) th').each( function (i) {
            var title = $(this).text();
            if(title === 'Aksi'){
                $(this).html('');
            } else {
                $(this).html( '<input type="text" style="text-align:center; font-family:system-ui, FontAwesome;" placeholder="&#xF002;" class="placeholder-fix" />' );
    
                $( 'input', this ).on( 'keyup change', function () {
                    if ( table.column(i).search() !== this.value ) {
                        table
                            .column(i)
                            .search( this.value )
                            .draw();
                    }
                } );
            }
        } );
    
        var table = $('#example').DataTable( {
            orderCellsTop: true,
            fixedHeader: true,
        } );
	} );
    </script>
@endsection